version: '3'

services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client:/client
    networks:
      - app-network

  # Backend
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

