version: '3'

services:

  # Frontend
  frontend:
    build:
      context: client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

    depends_on:
      - backend
    networks:
      - app-network

  # Backend
  backend:
    build:
      context: server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/app
    ports:
      - 9090:9090
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
