---
# This action should run on every push except on push to master

name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  golang-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Golang 1.17.0
        uses: actions/setup-go@v3
        with:
          go-version: "1.17.0"

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build the server
        run: go build .

      - name: Run vet & lint on the code
        run: |
          go vet .
          golint .

      - name: Run Go tests
        run: go test ./... -v

  javascript-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Check out the repo
      - uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build the client
        run: npm run build
