---
# This action should run on every push except on push to master
name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  golang-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.0" # The Go version to download (if necessary) and use.

      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # Run build of the application
      - name: Run build
        run: go build .
        working-directory: server

      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          go vet .
          golint .
        working-directory: server

      # Run testing on the code
      - name: Run testing
        run: go test ./... -v
        working-directory: server

  javascript-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Install dependencies
      - run: npm run ci
        working-directory: client

      # Build the project
      - run: npm run build
        working-directory: client
